#!/bin/bash

set -ue

res_dir=$CMB_HOME/res
graphs_dir=$CMB_HOME/graphs
bundle=$graphs_dir/graphs.tgz

rm -f $graphs_dir/*; mkdir -p $graphs_dir

for dir in $res_dir/*; do
  d=$(grep delay $dir/conf_info | cut -d= -f2)
  r=$(grep rw_ratio $dir/conf_info | cut -d= -f2)
  [[ $r = 0:1 ]] && r=upd || r=get
  c=$(grep consistency $dir/conf_info | cut -d= -f2)

  cp $dir/summary.png $graphs_dir/$d-$r-$c.png
done

tar cvzf $bundle $graphs_dir --exclude $bundle -C $CMB_HOME
