#!/bin/bash

in=(site)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue

site=$1

data_dir=$HOME/workspace/exp-data
unused_dir=$HOME/workspace/unused-data

rsync -avz --delete --progress $data_dir $site.g5k:
rsync -avz --delete --progress $unused_dir $site.g5k:
