#!/bin/bash

set -ue

site=sophia

# real sync
data_dir=$HOME/workspace/exp-data
rsync -avz --delete --progress $data_dir $site.g5k:

# archive (no --delete)
unused_dir=$HOME/workspace/unused-data
rsync -avz --progress $unused_dir $site.g5k:
