#!/bin/bash

set -ue
cd $CMB_HOME/res

for d in *; do
  [[ ! -e $d/summary.csv ]] && echo "$d,missing summary.csv" && continue
  [[ ! -e $d/conf_info ]] && echo "$d,missing conf_info" && continue
  
  errors=$(awk 'NR>1 {print $5 / $3}' $d/summary.csv)
  [[ $errors -eq 1 ]] && echo "$d,all errors" && continue
done

exit 0
