#!/bin/bash

in=(site)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue

site=$1
dst=$HOME/workspace

for d in g5k-scripts images; do
  rsync -avz --delete --progress $site.g5k:$d $dst
done
