#!/bin/bash

in=(site dir_in_workspace)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue

site=$1
dir=$2

rsync -avz --progress --delete $site.g5k:$dir $HOME/workspace
