#!/bin/bash

in=(site res_idx)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue
cd $CMB_HOME

site=$1
res_idx=$2

if [[ $res_idx == "all" ]]; then
  for i in {1..4}; do
    echo "get-res $i"
    $CMB_HOME/get-res $site $i &
  done; wait
  exit 0
fi

[[ $res_idx == - ]] && res_dir=res || res_dir=res.$res_idx

#rsync -avz --delete $site.g5k:$res_dir $CMB_HOME
rsync -avz $site.g5k:$res_dir $CMB_HOME
echo "Errors:"; egrep -r "\[error\]" $res_dir/*/srv-* || true

$CMB_HOME/index-res $res_dir
$CMB_HOME/proc-res $res_dir
$CMB_HOME/csv.rb $res_dir
