#!/bin/bash

in=(res_idx)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue
cd $CMB_HOME

res_idx=$1

site=rennes
res_dir=res.$res_idx

rsync -avz --exclude latest $site.g5k:$res_dir $CMB_HOME

$CMB_HOME/proc-res $res_dir
