#!/bin/bash

in=(res_dir)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue

res_dir=$1

param() {
  local d=$1; local p=$2
  grep "$p=" $d/conf_info | cut -d= -f2
}

idx=$res_dir/idx
rm -f $idx

for dir in $(find $res_dir/* -maxdepth 0 -type d); do
  k=""
  # see the list of actually used factors in csv.rb
  for p in consistency w tl_mode locality popularity rw_ratio delay delay_var \
           loss dupl corrupt reorder; do
    v=$(param $dir $p)
    k+=" "$v
  done

  echo $k $(basename $dir) >> $idx
done

exit 0
