#!/bin/bash

in=(dir_in_workspace site)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue

dir=$1
site=$2

rsync -avz --progress --delete $HOME/workspace/$dir $site.g5k:
