#!/bin/bash

set -ue

((threshold=40*60))
fend="rennes.g5k"

alarm() {
  msg=$1
  echo $msg
  mplayer -loop 220 alarm.wav &> /dev/null # 220 * 2.7s = 10min
}

while :; do
  [[ -z $(ssh $fend "oarstat -u | awk 'NR > 2 {print \$5}' | grep R") ]] && echo "No running job" && exit 0

  if [[ -z $(ssh $fend "ls cmb/run-all.log") ]]; then
    alarm "WARN: no run-all.log"
    break
  fi

  last_mod=$(ssh $fend "stat -c %y cmb/run-all.log")
  time_mod=$(date -d "$last_mod" +%s)
  now=$(date +%s)
  ((dt=$(date +%s)-time_mod)) || true # local now - remote last mod
  echo "Last mod: $last_mod (${dt}s)"

  if [[ $dt -gt $threshold ]]; then
    alarm "WARN: run-all halted"
    break
  fi

  sleep 120
done
