#!/bin/bash

set -ue

((threshold=40*60))
fend="rennes.g5k"

while :; do
  [[ -z $(ssh $fend "oarstat -u | awk 'NR > 2 {print \$5}' | grep R") ]] && echo "No running job" && exit 0

  last_mod=$(ssh $fend "stat -c %y cmb/run-all.log")
  time_mod=$(date -d "$last_mod" +%s)
  now=$(date +%s)
  ((dt=$(date +%s)-time_mod)) | true # local now - remote last mod
  echo "Last mod: $last_mod (${dt}s)"

  if [[ $dt -gt $threshold ]]; then
    echo "WARN: run-all halted"
    mplayer -loop 220 alarm.wav &> /dev/null # 220 * 2.7s = 10min
    break
  fi

  sleep 120
done
