#!/bin/bash

in=(site)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue

site=$1

((threshold=40*60))
fend="$site.g5k"

alarm() {
  msg=$1
  echo $msg
  mplayer -loop 220 alarm.wav &> /dev/null # 220 * 2.7s = 10min
}

log=$(ssh $fend "ls -t res/campaign*.log | head -1")
[[ -z $log ]] && echo "WARN: no log" && exit 1
while :; do
  [[ -z $(ssh $fend "oarstat -u | awk 'NR > 2 {print \$5}' | grep R") ]] && echo "No running job" && exit 0

  last_mod=$(ssh $fend "stat -c %y $log")
  time_mod=$(date -d "$last_mod" +%s)
  now=$(date +%s)
  ((dt=$(date +%s)-time_mod)) || true # local now - remote last mod
  echo "Last mod: $last_mod (${dt}s)"

  if [[ $dt -gt $threshold ]]; then
    alarm "WARN: run-all halted"
    break
  fi

  sleep 120
done
