#!/bin/bash

in=(res_dir dst_dir consist w mode rw_ratio loc pop delay)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue
cd $CMB_HOME

res_dir=$1
dst_dir=$2
shift 2

mkdir -p $dst_dir

src_dirs=$($CMB_HOME/show-res -d $res_dir $@ | tail -n +2 | cut -f6)
mv $src_dirs $dst_dir
