#!/bin/bash

set -ue
source $RIAK_CMP_HOME/env.sh
pushd $TMP_DIR > /dev/null

key=$(cat obj_keys) # starts with a /
vclock=$(cat obj_vclocks)
content=$(date)

ip=$(to_ip $1)
curl -v -X PUT -d "$content" -H "Content-Type: text/plain" -H "X-Riak-Vclock: $vclock" http://$ip:8098$key?returnbody=true 2>&1 | sed 's/< X-Riak-Vclock: \(.*\)/\1/w obj_vclocks'

popd > /dev/null
